### PR TITLE
fixes #19

### LINKED ISSUE #19: Regression on sum.run
83441b7289e42b7d4f9c2f12cb47f2bcb23f3a17 introduced an regression on sum.run. This changes was mado to fix a compilation issue with scala 2.10

```scala
[error] /home/joao/git/blocking-slick/src/test/scala/com/github/takezoe/slick/blocking/SlickBlockingAPISpec.scala:101: value run is not a member of slick.lifted.Rep[Option[Long]]
[error]       val sum = Users.map(_.id).sum.run
[error]                                     ^
[error] one error found
```

### PR DESCRIPTION
**Pull request by jtjeferreira**

### CODE REVIEW

File: src/main/scala/com/github/takezoe/slick/blocking/BlockingProfile.scala [hunk 1]
```diff
@@ -56,8 +56,8 @@ trait BlockingJdbcProfile extends BlockingRelationalProfile { profile: JdbcProfi
       }
     }
   
-    implicit class RepQueryExecutor[E: BaseTypedType](rep: Rep[E]){
```
Comment (jtjeferreira) [inline src/main/scala/com/github/takezoe/slick/blocking/BlockingProfile.scala]: reverting the commit that introduced this regression wasn't a solution because compilation in scala 2.10 was still failing.  the solution here is to directly call slick.lifted.RepShape.apply which is what other implicit conversions were doing under the wood
